# This file tells "conda" what to install in order to run the code. Things will
# be installed in a separate environment (with the name defined below) so that
# they don't interfere with other programs/projects.
name: dissertation-CHANGE-THIS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  # The basic Scipy stack
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  # Jupyter notebook
  - jupyter
  - jupyterlab
  # For executing tasks
  - make
  # The Fatiando a Terra packages
  - verde
  - harmonica
  - boule
  - pooch
